# MongoDB
mongodb_enabled: false
mongodb_connstring: mongodb://blackbox:blackbox@blackbox-mongo:9999

# Postgres
postgres_enabled: true
postgres_connstring: postgresql://blackbox:blackbox@blackbox-postgres:5432

# Storage providers
gdrive_enabled: false

# Database rotation
rotation_days: 7
