version: "3.7"
services:
  postgres:
    container_name: blackbox-postgres
    image: postgres:12
    environment:
      POSTGRES_USER: blackbox
      POSTGRES_PASSWORD: blackbox
    volumes:
      - ./docker/postgres/postgres_init.sql:/docker-entrypoint-initdb.d/init.sql

  mongo:
    container_name: blackbox-mongo
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: blackbox
      MONGO_INITDB_ROOT_PASSWORD: blackbox
    volumes:
      - ./docker/mongo/init_data:/init_data
      - ./docker/mongo/mongo_import.sh:/docker-entrypoint-initdb.d/mongo_import.sh

  redis:
    container_name: blackbox-redis
    build:
      context: .
      dockerfile: docker/redis/Dockerfile

  maria:
    container_name: blackbox-maria
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  mysql:
    container_name: blackbox-mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  blackbox:
    container_name: blackbox
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./blackbox.yaml:/blackbox/blackbox.yaml
      - ./main.py:/blackbox/main.py
      - ./blackbox:/blackbox/blackbox
    env_file:
      - docker/.env
    depends_on:
      - postgres
      - mongo
      - redis
      - maria
      - mysql