[tool.poetry]
name = "blackbox"
version = "2.1.0"
description = "Tool for automatic backups of databases"
authors = ["Leon Sandøy <leon.sandoy@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
pyyaml = "^5.3.1"
requests = "^2.25.1"
boto3 = "^1.16.51"
loguru = "^0.5.3"
jinja2 = "^2.11.2"
click = "^7.1.2"
dropbox = "^11.0.0"
pytelegrambotapi = "^3.7.7"

[tool.poetry.dev-dependencies]
pytest = "*"
pytest-cov = "^2.11.1"
pytest-mock = "^3.5.1"
flake8 = "^3.9.0"
flake8-isort = "^4.0.0"
pytest-subprocess = "^1.0.1"
requests-mock = "^1.8.0"
win32-setctime = "^1.0.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
blackbox = "blackbox.cli:cli"