name: Release to PyPI

on:
  release:
    types: [ published ]

jobs:
  publish-to-pipy:
    name: publish to pypi.org
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo and the submodules.
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.9"

      - name: Install Poetry >= 1.2.0a
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py -O &&
          python install-poetry.py --preview

      - name: Install dependencies
        run: poetry install

      - name: Install poetry-version-plugin
        run: poetry plugin add poetry-version-plugin

      - name: Build and publish to pypi
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }} &&
          poetry publish --build

  build-and-push-on-release:
    name: Build and push
    runs-on: ubuntu-latest
    needs: publish-to-pipy

    steps:
      # Check out the current repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Docker Buildx and log into DockerHub
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN  }}

      # Build and push the container to the GitHub Container
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          cache-from: type=registry,ref=lemonsaurus/blackbox:latest
          cache-to: type=inline
          tags: |
            lemonsaurus/blackbox:latest
            lemonsaurus/blackbox:${{ github.event.release.tag_name }}
