name: Release to PyPI

on:
  release:
    types: [ published ]

jobs:
  publish-pipy:
    name: publish to pypi.org
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo and the submodules.
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.9"

      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1  # https://github.com/marketplace/actions/publish-python-poetry-package
        with:
          python_version: '3.9.0'
          poetry_version: '==1.1.5'  # PIP version specifier syntax
          pypi_token: ${{ secrets.PYPI_TOKEN }}
          repository_name: 'blackbox-cli'
          repository_url: 'https://pypi.org/project/blackbox-cli/'
