# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Lint & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-lint:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.9.4 ]
        poetry-version: [ 1.1.5 ]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: Install poetry dependencies
        run: poetry install --no-interaction --no-root

      - name: Install poethepoet to use poe
        run: pip install poethepoet

      - name: Linting
        run: poe lint

      - name: Testing
        run: poe test